### ISSUE TITLE
Use semantic names for colors

### ISSUE THREAD

**Issue by barmac** [bpmn-io/properties-panel#15]
__Is your feature request related to a problem? Please describe__

Some of the colors in the properties panel are set via semantic names, e.g.

https://github.com/bpmn-io/properties-panel-next/blob/a0dadd1649bb248ea0ab72759e76bd905b707146/assets/properties-panel.css#L168-L174

but some are not:

https://github.com/bpmn-io/properties-panel-next/blob/a0dadd1649bb248ea0ab72759e76bd905b707146/assets/properties-panel.css#L79-L83

Let's use the first style as it allows to re-style the properties panel easier. So you don't override the properties directly:
```css
.bio-properties-panel-group {
  background-color: salmon;
}
```
but rather just change the custom property on the container level:

```css
.bio-properties-panel {
  --color-input-background: salmon
}
```

__Describe the solution you'd like__

Use semantic custom properties, e.g. `--color-group-background`.

__Describe alternatives you've considered__

Leave it as it is, but then it will be more work to introduce re-styling in the future.
